name: Build App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name scoutbook-macos scoutbook.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: scoutbook-macos
        path: dist/scoutbook-macos

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libnotify-dev libsdl2-dev libsm-dev libtiff-dev libxtst-dev freeglut3-dev libjpeg-dev libwebkit2gtk-4.0-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name scoutbook-linux scoutbook.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: scoutbook-linux
        path: dist/scoutbook-linux
